# Generated by Django 3.2 on 2021-05-01 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_auto_20210501_1419'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='user_profiles',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 1, 14, 25, 14, 954350)),
        ),
    ]
